/**
 * Claude Code hook integration for notifications.
 *
 * Agent-view maintains its own settings file (~/.agent-view/hooks/
 * claude-settings.json) that is passed to claude via `--settings` at launch —
 * the user's ~/.claude/settings.json is never touched. The hooks invoke
 * notify.sh, which fires a native OS notification and drops a signal file for
 * the TUI. Delivery lives in the script (not the TUI) on purpose: the TUI
 * event loop is frozen while attached to any session, and notifications must
 * work even when the TUI isn't running at all.
 */

import path from "path"
import os from "os"
import fs from "fs"

const HOOKS_DIR = path.join(os.homedir(), ".agent-view", "hooks")
const SETTINGS_PATH = path.join(HOOKS_DIR, "claude-settings.json")
const SCRIPT_PATH = path.join(HOOKS_DIR, "notify.sh")

export const NOTIFICATIONS_DIR = path.join(os.homedir(), ".agent-view", "notifications")

// The script reads the hook JSON payload on stdin. It exits silently unless
// launched from an agent-view session ($AGENT_ORCHESTRATOR_SESSION), respects
// the notifications toggle in config.json, and skips the OS notification when
// a client is attached to the session's tmux window (the user is watching).
const NOTIFY_SCRIPT = `#!/bin/bash
# Generated by agent-view — do not edit, changes are overwritten on app start.
EVENT="\${1:-stop}"
[ -z "$AGENT_ORCHESTRATOR_SESSION" ] && exit 0

PAYLOAD=$(cat 2>/dev/null || true)

CONFIG="$HOME/.agent-view/config.json"
if [ -f "$CONFIG" ] && grep -q '"notifications"[[:space:]]*:[[:space:]]*false' "$CONFIG"; then
  exit 0
fi

# Suppress the OS notification when someone is attached to this tmux session
SKIP_NOTIFY=""
if [ -n "$TMUX_PANE" ]; then
  ATTACHED=$(tmux -L agent-view display-message -p -t "$TMUX_PANE" '#{session_attached}' 2>/dev/null)
  if [ -n "$ATTACHED" ] && [ "$ATTACHED" != "0" ]; then
    SKIP_NOTIFY=1
  fi
fi

TITLE="\${AGENT_ORCHESTRATOR_TITLE:-Agent View}"
if [ "$EVENT" = "stop" ]; then
  MESSAGE="Finished — waiting for you"
else
  MESSAGE=$(printf '%s' "$PAYLOAD" | sed -n 's/.*"message"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p' | head -1)
  [ -z "$MESSAGE" ] && MESSAGE="Needs your attention"
fi

if [ -z "$SKIP_NOTIFY" ]; then
  case "$(uname)" in
    Darwin)
      TN=""
      [ -x /opt/homebrew/bin/terminal-notifier ] && TN=/opt/homebrew/bin/terminal-notifier
      [ -z "$TN" ] && [ -x /usr/local/bin/terminal-notifier ] && TN=/usr/local/bin/terminal-notifier
      if [ -n "$TN" ]; then
        "$TN" -title "$TITLE" -message "$MESSAGE" -group "agent-view-$AGENT_ORCHESTRATOR_SESSION" >/dev/null 2>&1
      else
        ESC_MSG=\${MESSAGE//\\\\/\\\\\\\\}
        ESC_MSG=\${ESC_MSG//\\"/\\\\\\"}
        ESC_TITLE=\${TITLE//\\\\/\\\\\\\\}
        ESC_TITLE=\${ESC_TITLE//\\"/\\\\\\"}
        osascript -e "display notification \\"$ESC_MSG\\" with title \\"$ESC_TITLE\\"" >/dev/null 2>&1
      fi
      ;;
    Linux)
      command -v notify-send >/dev/null 2>&1 && notify-send "$TITLE" "$MESSAGE" >/dev/null 2>&1
      ;;
  esac
fi

# Signal file for the TUI (powers the needs-attention glyph)
NOTIF_DIR="$HOME/.agent-view/notifications"
mkdir -p "$NOTIF_DIR"
printf '{"event":"%s","sessionId":"%s","timestamp":%s}\\n' "$EVENT" "$AGENT_ORCHESTRATOR_SESSION" "$(date +%s)" > "$NOTIF_DIR/$AGENT_ORCHESTRATOR_SESSION.json"
exit 0
`

const HOOK_SETTINGS = {
  hooks: {
    Stop: [
      {
        hooks: [
          { type: "command", command: `bash "$HOME/.agent-view/hooks/notify.sh" stop` }
        ]
      }
    ],
    Notification: [
      {
        hooks: [
          { type: "command", command: `bash "$HOME/.agent-view/hooks/notify.sh" notification` }
        ]
      }
    ]
  }
}

function writeIfChanged(filePath: string, content: string, mode: number): void {
  let existing: string | null = null
  try {
    existing = fs.readFileSync(filePath, "utf-8")
  } catch {
    // File doesn't exist yet
  }
  if (existing !== content) {
    fs.writeFileSync(filePath, content, { mode })
  }
}

/**
 * Ensure the hook settings file and notify script exist and are up to date.
 * Returns the settings path for use with `claude --settings`.
 * Safe to call often — writes only when content changed.
 */
export function ensureHookFiles(hooksDir: string = HOOKS_DIR): string {
  const settingsPath = path.join(hooksDir, "claude-settings.json")
  try {
    fs.mkdirSync(hooksDir, { recursive: true, mode: 0o700 })
    fs.mkdirSync(NOTIFICATIONS_DIR, { recursive: true, mode: 0o700 })
    writeIfChanged(settingsPath, JSON.stringify(HOOK_SETTINGS, null, 2) + "\n", 0o600)
    writeIfChanged(path.join(hooksDir, "notify.sh"), NOTIFY_SCRIPT, 0o700)
  } catch (err) {
    console.error("Failed to write claude hook files:", err)
  }
  return settingsPath
}

export function getHookSettingsPath(): string {
  return SETTINGS_PATH
}
